trigger:
- azure-pipelines-test   # or your branch

pool:
  vmImage: ubuntu-latest

- stage: Build
  jobs:
  - job: PackageJob
    steps:
    - checkout: self
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)'
        Contents: '**'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'www'
        publishLocation: 'Container'


- stage: DeployDev
  jobs:
  - deployment: DeployDevJob
    environment: 'development'
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: www
          - task: AzureStaticWebApp@0
            inputs:
              # Point this to the folder created by the 'download' step
              app_location: 'www' 
              # This prevents the task from searching for a package.json/build script
              skip_app_build: true 
              azure_static_web_apps_api_token: $(deployment_token)


# Deploy step
# - task: AzureStaticWebApp@0
#   displayName: "Deploy to Azure Static Web App"
#   inputs:
#     app_location: "/"              where your site lives
#     output_location: ""            leave empty if no build output
#     api_location: ""               leave empty unless using API
#     azure_static_web_apps_api_token: $(deployment_token)