trigger:
- azure-pipelines-test

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  displayName: 'Build Static Site'
  jobs:
  - job: BuildJob
    steps:
    - checkout: self
    

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '.' 
        ArtifactName: 'drop'
        publishLocation: 'Container'

- stage: DeployDev
  displayName: 'Deploy to Dev'
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/azure-pipelines-test')
  dependsOn: Build
  jobs:
  - deployment: DeployDevJob
    environment: 'dev'
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: drop
          
          - task: AzureStaticWebApp@0
            inputs:
              app_location: "$(Pipeline.Workspace)/drop"
              # This tells Azure: "Don't try to compile anything, just take the files"
              skip_app_build: true 
              azure_static_web_apps_api_token: $(deployment_token)
